Repository devopsloft/dpline, pull requests merged in 2019-01, with the labels that each got.

#7 Add Jenkins deployment script
  README.md
  deploy_dpline.sh
  jenkins/deploy_docker.sh
  setup/prepare_host.yml
  setup/roles/install_docker/tasks/main.yml
Labels: enhancement

#9 deploy rabbitmq
  rabbitmq/deploy.sh
Labels: enhancement

#17 Prometheus
  README.md
  jenkins/deploy.sh
  prometheus/deploy.sh
Labels: enhancement

#29 switched base image to fedora29
  README.md
  Vagrantfile
  bootstrap.sh
Labels: enhancement

#31 verify vagrant/virtualbox installed
  dpline-env.sh
Labels: Task

#30 Ansible role docker
  Vagrantfile
  bootstrap.sh
  jenkins/Dockerfile
  jenkins/deploy.sh
  requirements.yml
  setup/prepare_host.yml
  setup/roles/install_docker/tasks/main.yml
Labels: Task, bug

#34 Add basic CI
  .travis.yml
  README.md
  dpline/parser.py
  test-requirements.txt
Labels: enhancement
